name: Lib_core
main: com.fyxridd.lib.core.api.CorePlugin
version: 1.11.0
load: startup
depend: [ProtocolLib, PacketWrapper]
softdepend: [Vault, Lib_msg]
commands:
  f:
    description: FuncManager
    usage: /<command> ?
  s:
    description: InputManager
    usage: /<command> ?
  per:
    description: CmdManager
    usage: /<command> ?
  group:
    description: CmdManager
    usage: /<command> ?