#功能:
#>哈希列表(列表的有序性,检测的高效性,集合的唯一性,但占用内存更多)
#>名字映射
#  >世界名映射
#  >药效名映射
#  >附魔名映射
#  >实体名映射
#  >物品方块名映射
#>配置管理
#  >重新读取配置
#  >配置读取异常日志
#>功能管理
#  >对外提供:
#    >功能接口
#    >玩家操作事件
#  >目标:
#    >统一管理服务器的所有功能
#  >形式:
#    >统一显示,主要是功能无效时的颜色替换
#    >统一限制,主要是功能操作时的检测禁止
#>语言管理
#>显示管理
#>时间
#>经济
#>权限
#>附加属性
#>输入管理
#>玩家真名
#>速度
#>Tps
#>真实伤害
#  >真实伤害事件
#>NBT编辑类
#>事务
#>提示事务
#>进入方块类型
#>聊天管理
#  >玩家聊天事件
#>标题
#>字符串匹配
#  >模式:
#    >1. 普通匹配,格式'1 y/n 匹配串',y/n表示大小写敏感/不敏感
#    >2. 正则匹配,格式'2 正则串'
#################################
#####       语言文件        #####
#################################
lang:
  default: "cn"                #默认语言(指不明确指定语言的情况下)
  error: "en"                  #错误时使用语言(指指定的语言配置不存在时使用的语言配置)
#################################
#####         描述          #####
#################################
#如果插件的配置文件中有此项,则会被配置管理自动读取并保存为插件的描述信息
description:                     #字符串列表,Lib插件的配置文件重新读取描述
  - "&7- 重新读取config.yml"
  - "&7- 重新读取language.yml"
#################################
#####         配置          #####
#################################
debug: true                      #是否开启调试模式
lib_core_admin: "lib.core.admin"  #插件管理权限
#伤害修正
#格式'物品ID 伤害'
fixDamage:
  - "256 3"
  - "257 4"
  - "258 5"
  - "269 1"
  - "270 2"
  - "271 3"
  - "273 2"
  - "274 3"
  - "275 4"
  - "277 4"
  - "278 5"
  - "279 6"
  - "284 1"
  - "285 2"
  - "286 3"
  - "267 6"
  - "268 4"
  - "272 5"
  - "276 7"
  - "283 4"
#################################
#####       哈希列表        #####
#################################
#################################
#####        名字映射       #####
#################################
#可以使用相对路径(是相对于服务端所在文件夹的路径)
names:
  path: "plugins/Lib_core/names.yml"
#################################
#####       配置管理        #####
#################################
config:
  adminPer: "lib.core.config"     #配置管理的管理权限
  log:
    prefix: "[{1}][{2}] "      #日志前缀格式,'{1}'代表时间,'{2}'代表插件名
    dateFormat: "yyyy-MM-dd HH:mm:ss"  #时间格式
#################################
#####       功能管理        #####
#################################
funcManager:
  invalid:                       #无效时(无此功能或禁用)
    color: "8"
    format: "m"
  notOn:                         #(对玩家)未开启时
    color: "7"
    format: ""
  banFuncs:                      #禁用的功能列表(有时因各种原因会临时禁用)
    - "xxx"
  funcMap:                       #功能映射,'使用名 功能名',使用名以短为标准,功能名以容易理解为标准(改动可能会出异常)
    - "cm ConfigManager"         #配置管理
    - "sm ShowManager"           #显示管理
    - "tm TransactionManager"    #事务管理
    - "tp TipTransaction"        #提示事务
    - "pe PageEdit"              #页面编辑
    - "ap AdPoint"               #广告点
    - "mp MonPoint"              #怪物点
    - "sa ShowAction"            #显示动作
    - "ie ItemsEdit"             #物品编辑框
    - "re Rewards"               #奖励
    - "fd Friend"                #好友
    - "bl BlackList"             #黑名单
    - "ch Channel"               #聊天频道
    - "cc ChatColor"             #聊天颜色格式
    - "hp HomePage"              #个人主页
    - "ad Ad"                    #广告
    - "cr ClearManager"          #清理
    - "si Sit"                   #坐椅
    - "ld Land"                  #领地
    - "dm DeathMessage"          #死亡信息
    - "ta Tpa"                   #请求传送
    - "sn Spawn"                 #重生点
    - "he Home"                  #家
    - "kt Kit"                   #物品包
    - "ah Auth"                  #登录
    - "tt Ticket"                #点券
    - "vp Vip"                   #VIP
    - "se SkillEasy"             #简易技能
    - "ve Vote"                  #投票
    - "sp Shop"                  #商店
    - "an Auction"               #拍卖
    - "fc Func"                  #功能
    - "qt Quest"                 #任务
    - "ar Answer"                #答题
    - "ll Level"                 #称号
    - "hs House"                 #家园
    - "fl Formal"               #正式用户
    - "sy Sky"                  #空岛
    - "me Mine"                 #矿洞
    - "ee Exchange"            #交换
    - "ct Chat"                 #聊天
    - "rk Rank"                #称号
    - "wn Weapon"              #武器
    - "ce Cert"                #领地券
    - "te Trade"               #交易
    - "mg Msg"                 #前后缀
    - "gp Group"               #帮派
    - "sl Stall"               #摆摊
    - "mz MonZone"             #副本
    - "st Store"               #店铺模型
    - "sv StoreView"           #店铺界面
    - "ss StoreSign"           #店铺牌子
    - "cd Card"                 #卡密
#################################
#####       语言管理        #####
#################################
#################################
#####       显示管理        #####
#################################
show:
  deadLoopLevel: 5              #重复调用几层判定为死循环,>=1
  cancel:                       #检测退出页面
    interact: true              #玩家与方块交互时
    animation: false            #玩家挥动手时
    attack: true                #玩家攻击或受攻击时
    chat: false                 #玩家聊天时
    chatCancel: true            #chat为false时,玩家在显示界面时是否取消其发出的聊天信息
    shoot: true                  #发射时
  maxBackPage: 10               #最大保存的返回页面数,>=0
  line: 25                      #页面行数,补的空行数=line-有内容的行数,>=1
#################################
#####         时间          #####
#################################
#################################
#####         经济          #####
#################################
eco:
  max: 10000000                  #玩家钱上限,>=0
  priority:                      #优先级,'名字 优先级(整数)',默认0级,目前有两个处理器:eco,vault #!!!vault需要前置Vault插件
    - "eco 100"
    - "vault 50"
#################################
#####         权限          #####
#################################
per:
  priority:                      #优先级,'名字 优先级(整数)',默认0级,目前有两个处理器:per,vault #!!!vault需要前置Vault插件
    - "per 100"
    - "vault 50"
  other:
    vaultDefaultWorld: "world"   #vault权限插件是分世界的,如果检测权限时无法获取到世界,则用此世界代替
#################################
#####       附加属性        #####
#################################
#################################
#####       输入管理        #####
#################################
input:
  cancel:                        #(什么情况下)取消输入
    interact: true
    animation: false
  allow:                         #允许的输入方式
    chat: true
    cmd: true
#################################
#####       玩家真名        #####
#################################
realName:
  enable: true                   #false时不会限制玩家进服
#################################
#####          速度         #####
#################################
speed:
  short:
    clearInterval: 3             #短期的清理(检测)间隔,单位秒,>=1
    #提示: 短期间隔可分为命令与非命令的检测
    #>如果是命令的间隔检测,则间隔过短时适合使用NCP自带的命令限制功能(如1,2级);间隔长时使用没有问题
    #>如果是非命令的检测(如玩家踩踏板触发事件的频率检测),则使用没有问题
    levels:                      #等级列表,从上到下为1,2,3...级
      - 250
      - 550
      - 1400
  side:                          #侧边栏提示(需要前置插件Lib_msg)(可选)
    enable: true                 #不开启或前置不满足则显示在聊天栏(在聊天栏显示时,不会强制显示,因此有界面时显示不出)
    clear: 1250                  #多少ms后清除提示,>=1
#################################
#####          Tps         #####
#################################
#################################
#####       真实伤害        #####
#################################
#################################
#####       NBT编辑类       #####
#################################
#################################
#####         事务          #####
#################################
#################################
#####       提示事务        #####
#################################
#################################
#####   进入/走上方块类型   #####
#################################
enterBlockType:
  interval: 7                   #检测间隔,单位tick,>=1
#################################
#####        聊天管理       #####
#################################
chat:
  maxSaves: 30                  #延时显示的最大保存条数,>=0
  delayShow:
    interval: 10                #延时显示的间隔,单位tick,>=1
    prefix: "&7\u2191"         #延时显示的聊天信息前缀,可为空(会加到整个聊天信息前,包括玩家名)
#################################
#####          标题         #####
#################################
title:
  time: 4                      #单位tick,默认显示时间=信息总长度*time,>=0
  fadeIn: 15                  #单位tick,>=0
  fadeOut: 15                 #单位tick,>=0
  interval: 15                #单位tick,>=0,连接显示的间隔(一条显示结束后,下一条显示开始前等待的时间)