列表:
   类名: ConfigContext
   属性:
     pluginName: 插件名
   方法:
     getDescription():  描述信息文字,内含\n换行,如'xxx\nyyy'

显示效果:
=====================[配置管理]=====================
------------------[注册的插件列表]----------------
 [xxx]  [xxx]  [xxx]
 [xxx]  [xxx]  [xxx]
 [xxx]  [xxx]  [xxx]
 [xxx]  [xxx]  [xxx]
 [xxx]  [xxx]  [xxx]
  -<列表>-  <<  <  1/10  >  >>  -<列表>-
=====[返回]=========[操作提示]=========[退出]=====
xxxxxxxx